### ISSUE TITLE
Error while computing PD

### ISSUE THREAD

**Issue by p-neves** [KaiHsiangHu/iNEXT.3D#10]
[Archive.zip](https://github.com/KaiHsiangHu/iNEXT.3D/files/14358311/Archive.zip)

Hi:

I'm trying to use the iNEXT3D function to compute PD with the attached data (2 Rds objects with the species abundances per location and the phylo tree), by using:

'output_PD_abun <- iNEXT3D(Abund, diversity = 'PD', q = c(0, 1, 2), nboot = 20, PDtree = PDtree$phylo)' 

 However, I get the following error: "Error: Number of sampling units should be a positive value."

Any ideas what the problem is?

Thanks in advance:

Pedro

**Comment by KaiHsiangHu** [comment]
Dear p-neves,

I'm so sorry about this error from my data checking. I have fixed this problem . Please re-download iNEXT.3D from my github or Anne Chao's github. And I will submit the latest version to CRAN within these days.

Best regards

**Comment by p-neves** [comment]
Hi:
Thanks a lot for the rapid fix. It works now with my data.

All the best:

Pedro
