### ISSUE TITLE
Error in Li_b[isn0, , drop = F] : (subscript) logical subscript too long

### ISSUE THREAD

**Issue by p-neves** [KaiHsiangHu/iNEXT.3D#11]
Hi:

I'm trying to compute PD using the function "ObsAsy3D". However I get the error "Error in Li_b[isn0, , drop = F] : (subscript) logical subscript too long" and I have no idea how to troubleshoot it. Any hints of where I could start?

Thanks in advance:
Pedro

**Comment by p-neves** [comment]
I can also send you the data via PM, if you think its useful.

All the best:
Pedro

**Comment by KaiHsiangHu** [comment]
Dear @p-neves ,

Thank you very much for the question. I haven't met this error before. Can you please take a screen shot about your phylogenetic tree structure, or send me a part of your abundance data and tree?
I guess the tree structure isn't qualified for iNEXT.3D.

Thanks again
Best regards

**Comment by p-neves** [comment]
Hi:
Can you send me your e-mail address (via nevesdiver at gmail dot com) so I can PM you my data objects?

Cheers:
Pedro

**Comment by KaiHsiangHu** [comment]
Dear @p-neves :

Of course!  Here is my email:
river19951224@gmail.com

Thank you very much.
Best regards
